[package]
name = "dkvz-blog-backend"
version = "0.1.0"
authors = ["DkVZ <github@dkvz.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
